### ISSUE TITLE
NullPointerException - RandomItemSearch

### ISSUE THREAD

**Issue by Fabo0814** [Fabo0814/NewChallenges#1]
### Description

Sobald auf ein Item im Inventar geklickt wird produziert das Plugin eine NPE.

### Stacktrace

[23:26:55 ERROR]: Could not pass event InventoryClickEvent to NewChallenges v1.0.0-alpha
java.lang.NullPointerException: null
at eu.fabo0814.newchallenges.challenges.RandomItemSearch.onClick(RandomItemSearch.java:61) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor23.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Purpur-710]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Purpur-710]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Purpur-710]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Purpur-710]
at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2490) ~[patched_1.16.1.jar:git-Purpur-710]
at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.1.jar:git-Purpur-710]
at net.minecraft.server.v1_16_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.1.jar:git-Purpur-710]
at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.1.jar:git-Purpur-710]
at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Purpur-710]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Purpur-710]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Purpur-710]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Purpur-710]
at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1205) ~[patched_1.16.1.jar:git-Purpur-710]
at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1198) ~[patched_1.16.1.jar:git-Purpur-710]
at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Purpur-710]
at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1174) ~[patched_1.16.1.jar:git-Purpur-710]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1018) ~[patched_1.16.1.jar:git-Purpur-710]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.1.jar:git-Purpur-710]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Comment by Fabo0814** [comment]
Fixed
