### ISSUE TITLE
SpeedCraft - StackOverflowError

### ISSUE THREAD

**Issue by Fabo0814** [Fabo0814/NewChallenges#13]
### Description

Kein Item wird gezogen und die Challenge nicht wie erwartungsgemäß beendet.

### Stacktrace

```
[11:49:38] [Server thread/ERROR]: Could not pass event InventoryCloseEvent to NewChallenges v1.0.0
java.lang.StackOverflowError: null
	at com.lmax.disruptor.MultiProducerSequencer.tryNext(MultiProducerSequencer.java:167) ~[patched_1.16.1.jar:git-Purpur-710]
	at com.lmax.disruptor.MultiProducerSequencer.tryNext(MultiProducerSequencer.java:158) ~[patched_1.16.1.jar:git-Purpur-710]
	at com.lmax.disruptor.RingBuffer.tryPublishEvent(RingBuffer.java:477) ~[patched_1.16.1.jar:git-Purpur-710]
	at org.apache.logging.log4j.core.async.AsyncLoggerDisruptor.tryPublish(AsyncLoggerDisruptor.java:205) ~[patched_1.16.1.jar:git-Purpur-710]
	at org.apache.logging.log4j.core.async.AsyncLogger.publish(AsyncLogger.java:166) ~[patched_1.16.1.jar:git-Purpur-710]
	at org.apache.logging.log4j.core.async.AsyncLogger.logWithThreadLocalTranslator(AsyncLogger.java:162) ~[patched_1.16.1.jar:git-Purpur-710]
	at org.apache.logging.log4j.core.async.AsyncLogger.logMessage(AsyncLogger.java:132) ~[patched_1.16.1.jar:git-Purpur-710]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2091) ~[patched_1.16.1.jar:git-Purpur-710]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1988) ~[patched_1.16.1.jar:git-Purpur-710]
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1960) ~[patched_1.16.1.jar:git-Purpur-710]
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:733) ~[patched_1.16.1.jar:git-Purpur-710]
	at org.bukkit.craftbukkit.v1_16_R1.util.ForwardLogHandler.publish(ForwardLogHandler.java:32) ~[patched_1.16.1.jar:git-Purpur-710]
	at java.util.logging.Logger.log(Logger.java:738) ~[?:1.8.0_275]
	at java.util.logging.Logger.doLog(Logger.java:765) ~[?:1.8.0_275]
	at java.util.logging.Logger.log(Logger.java:876) ~[?:1.8.0_275]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.1.jar:git-Purpur-710]
	at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1421) ~[patched_1.16.1.jar:git-Purpur-710]
	at net.minecraft.server.v1_16_R1.EntityPlayer.closeInventory(EntityPlayer.java:1432) ~[patched_1.16.1.jar:git-Purpur-710]
	at net.minecraft.server.v1_16_R1.EntityPlayer.openContainer(EntityPlayer.java:1304) ~[patched_1.16.1.jar:git-Purpur-710]
	at org.bukkit.craftbukkit.v1_16_R1.entity.CraftHumanEntity.openWorkbench(CraftHumanEntity.java:354) ~[patched_1.16.1.jar:git-Purpur-710]
	at eu.fabo0814.newchallenges.challenges.SpeedCraft.closeInventory(SpeedCraft.java:162) ~[?:?]
```

**Comment by Fabo0814** [comment]
Behoben.
